[package]
name = "confetti"
version = "0.1.0"
edition = "2024"

[dependencies]
bytemuck = "1.23.1"
env_logger = "0.11.8"
libloading = "0.8.8"
pollster = "0.4.0"
rand = "0.9.2"
raw-window-handle = "0.6.2"
smithay-client-toolkit = "0.19.2"
wayland-client = "0.31.11"
wgpu = "26.0.1"
winit = "0.30.12"
